[package]

name = "libnotify-sys"
version = "0.0.2"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
license = "MIT"
description = "FFI bindings to libnotify"
readme = "README.md"
repository = "https://github.com/crumblingstatue/rust-libnotify-sys"
keywords = ["libnotify", "notification"]

build = "build.rs"
links = "libnotify"

[dependencies]
glib-2_0-sys = "*"
gobject-2_0-sys = "*"

[build-dependencies]
pkg-config = "0.3"
