[package]

name = "libnotify-sys"
version = "0.0.1"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

build = "build.rs"
links = "libnotify"

[dependencies]
glib-2_0-sys = "*"
gobject-2_0-sys = "*"

[build-dependencies]
pkg-config = "0.3"
