[package]

name = "libnotify-sys"
version = "0.0.1"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

build = "build.rs"
links = "libnotify"

[dependencies.glib-2_0-sys]
git = "https://github.com/gi-rust/glib-sys.git"

[build-dependencies]
pkg-config = "0.3"
